job_str: |-
  &GLOBAL
    PROJECT $JOB_NAME$
    RUN_TYPE MD
    PRINT_LEVEL MEDIUM
  &END GLOBAL

  &MOTION
    &MD
      ENSEMBLE NVT
      TEMPERATURE [K] 94
      TIMESTEP [fs] 0.5
      STEPS 100
      &THERMOSTAT
        REGION GLOBAL
        TYPE CSVR
          &CSVR
            TIMECON [fs] 1.0
          &END
      &END
    &END MD
    &PRINT
      &TRAJECTORY
        &EACH
          MD 20
        &END EACH
      &END TRAJECTORY
      &VELOCITIES OFF
      &END VELOCITIES
      &FORCES OFF
      &END FORCES
      &RESTART
        &EACH
          MD 20
        &END EACH
      &END RESTART
    &END PRINT
  &END MOTION


  &FORCE_EVAL
    METHOD Quickstep
    &DFT
      BASIS_SET_FILE_NAME  $PRM_PATH$/dzvp_pbe_gth_basis.prm
      POTENTIAL_FILE_NAME  $PRM_PATH$/gth_pbe_functional.prm
      MULTIPLICITY 1

      &MGRID
        NGRIDS 7
        CUTOFF [Ry] 280
      &END

      &POISSON
        PERIODIC XYZ
      &END POISSON
      &SCF              
        SCF_GUESS ATOMIC
        EPS_SCF 5.0E-6
        MAX_SCF 1000
        &PRINT
          &RESTART OFF
          &END
        &END

        &OT
          MINIMIZER CG
          LINESEARCH 3PNT
        &END OT

      &END SCF
      &XC               
        &XC_FUNCTIONAL PBE
        &END XC_FUNCTIONAL
      &END XC

      &PRINT
        &E_DENSITY_CUBE ON
          APPEND T
          ADD_LAST SYMBOLIC
        &END E_DENSITY_CUBE
        &MO_CUBES
          NLUMO 5
          NHOMO 5
          WRITE_CUBE .TRUE.
          &EACH
            MD 50
          &END
        &END
      &END

    &END DFT

    &SUBSYS
      &CELL
        ABC $DIMENSIONS$
        PERIODIC XYZ 
      &END CELL
      &TOPOLOGY         
        &CENTER_COORDINATES
        &END
        COORD_FILE_FORMAT xyz
        COORD_FILE_NAME  $XYZ_FILE$
      &END
      &KIND H
        ELEMENT H
        BASIS_SET DZVP-MOLOPT-PBE-GTH-q1
        POTENTIAL GTH-PBE-q1
      &END KIND
      &KIND C
        ELEMENT C
        BASIS_SET DZVP-MOLOPT-PBE-GTH-q4
        POTENTIAL GTH-PBE-q4
      &END KIND
      &KIND N
        ELEMENT N
        BASIS_SET DZVP-MOLOPT-PBE-GTH-q5
        POTENTIAL GTH-PBE-q5
      &END KIND
    &END SUBSYS
  &END FORCE_EVAL