job_str: |-
  units real
  boundary p p p
  atom_style full
  kspace_style pppm 1e-3

  pair_style lj/cut/coul/long 8.0
  bond_style harmonic
  angle_style harmonic
  dihedral_style opls
  special_bonds lj/coul 0.0 0.0 0.5

  read_data $DATA$
  group azo id <= $ATOMS$
  group meth subtract all azo
  group none subtract all azo meth

  pair_modify mix geometric
  $PAIR_COEFFS$

  dump 1 all xyz 10000 $NAME$.xyz
  dump_modify 1 element $ELEMENTS$
  dump_modify 1 sort id

  dump 2 all custom 10000 $NAME$_wbox.dump id type xu yu zu
  dump_modify 2 element $ELEMENTS$
  dump_modify 2 sort id

  thermo 50
  thermo_style custom $THERMO$

  min_style cg 
  minimize 1e-25 1e-25 5000 10000

  timestep 1.0
  neigh_modify check yes every 1 delay 0

  run_style respa 4 2 2 2 inner 2 4.5 6.0 middle 3 7.0 8.0 outer 4

  fix 1 all npt temp 10.0 10.0 50 aniso 1.45 1.45 1000
  run 10000
  unfix 1  

  velocity all create 94.0 1 rot yes dist gaussian

  fix 2 all npt temp 94.0 94.0 100.0 aniso 1.45 1.45 1000
  run 12000000
  unfix 2