job_str: |-
  units real
  boundary p p p
  atom_style full
  kspace_style pppm 5e-4

  pair_style lj/cut/coul/long 8.0
  bond_style harmonic
  angle_style harmonic
  dihedral_style opls
  special_bonds lj/coul 0.0 0.0 0.5

  read_data $DATA$
  group azo id <= $ATOMS$
  group nitro type 4
  group meth subtract all azo
  group none subtract all azo meth
  group acrylmol molecule == 3

  pair_modify mix geometric
  $PAIR_COEFFS$

  dump 1 all xyz 10000 $NAME$.xyz
  dump_modify 1 element $ELEMENTS$
  dump_modify 1 sort id

  dump 2 all custom 10000 $NAME$_wbox.dump id type xu yu zu
  dump_modify 2 element $ELEMENTS$
  dump_modify 2 sort id

  fix 1 acrylmol smd cvel 100 0.0000001 tether -1.7 -2.1 13.0 0.0

  thermo 50
  thermo_style custom $THERMO$

  min_style cg 
  minimize 1e-25 1e-25 5000 10000

  timestep 1.0
  neigh_modify check yes every 1 delay 0

  fix 2 all nvt temp 94.0 94.0 100.0
  run 20000000  

