xyz: "azo_nvt_equil.xyz"
sim: smd
center: True
population:
  acrylonitrile: 16
  methane: 48
params: "ligpargen.prm"
box_dims:
  - [6.2, 7.5, 9.25]
  - [-6.2, -7.5, -9.25]
cell_shape:
  sg: None
  angles: [90, 90, 90]
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "temp"
  - "press"
  - "f_1[6]"
  - "f_1[7]"
velocity: "none"