xyz: "rahm_monolayer_16.xyz"
sim: equil
center: True
population:
  acrylonitrile: 16
  methane: 48
params: "ligpargen.prm"
box_dims:
  - [6.2, 7.5, 9.25]
  - [-6.2, -7.5, -9.25]
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "c_pe"
  - "temp"
  - "press"
velocity: "none"