xyz: /scratch16/pclancy3/divya/azotosome/cp2k/221_md_res/221_md_res-1.restart
sim: nvt
center: True
population:
  acrylonitrile: 16
  methane: 48
params: "stevenson2.prm"
box_dims:
  # - [5.6, 6.8, 9.1]
  # - [-5.6, -6.8, -9.1]
  # box14 - [7, 7, 9.1]
  # - [-7, -7, -9.1]
  # box2- [6, 7, 10.5]
  # - [-6, -7, -10.5]
  - [5.6, 6.85, 10.5]
  - [-5.6, -6.85, -10.5]
cell_shape:
  sg: None
  angles: [90, 90, 90]
meth_start: 3.0
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "temp"
  - "press"
velocity: "none"