xyz: "tianle_azo.xyz"
sim: nvt
center: True
population:
  acrylonitrile: 4
  methane: 0
params: "stevenson2.prm"
box_dims:
  - [3.6, 3.5, 13.5]
  - [-3.6, -3.5, -13.5]
cell_shape:
  sg: 0
  angles: [90, 90, 90]
meth_start: 3.0
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "temp"
  - "press"
velocity: "none"