xyz: "pn21a_unit_boxrel.xyz"
sim: nvt
center: True
population:
  acrylonitrile: 4
  methane: 0
params: "stevenson2.prm"
box_dims:
  - [7.27, 6.32, 8.43]
  - [0, 0, 0]
cell_shape:
  sg: 0
  angles: [90, 90, 90]
meth_start: 3.0
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "temp"
  - "press"
velocity: "none"