xyz: "rahm_pn21a_small_222.xyz"
sim: nvt
center: True
population:
  acrylonitrile: 32
  methane: 0
params: "stevenson2.prm"
box_dims:
  - [14.4, 10.8, 16.72]
  - [0, 0, 0]
cell_shape:
  sg: 0
  angles: [90, 90, 90]
meth_start: 3.0
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "temp"
  - "press"
velocity: "none"