box_dims:
- - 6.255
  - 6.695
  - 10.5
- - -6.255
  - -6.695
  - -10.5
cell_shape:
  angles:
  - 90
  - 90
  - 90
  sg: None
center: true
meth_start: 3.0
params: stevenson2.prm
population:
  acrylonitrile: 16
  methane: 43
sim: nvt
thermo:
- step
- etotal
- ke
- pe
- temp
- press
velocity: none
xyz: stag_packx40y35_221.xyz
