xyz: "tianle_64.xyz"
sim: equil
center: True
population:
  acrylonitrile: 64
  methane: 118
params: "ligpargen.prm"
box_dims:
  - [12.5, 12.0, 9]
  - [-12.5, -12.0, -9]
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "temp"
  - "press"
velocity: "none"
