xyz: "tianle_azo_meth_241.xyz"
sim: nvt
center: True
population:
  acrylonitrile: 32
  methane: 96
params: "stevenson2.prm"
box_dims:
  - [5.71, 13.61, 10.5]
  - [-5.71, -13.61, -10.5]
cell_shape:
  sg: None
  angles: [90, 90, 90]
meth_start: 3.0
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "temp"
  - "press"
velocity: "none"