xyz: "tianle_azo_221.xyz"
sim: nvt
center: True
population:
  acrylonitrile: 16
  methane: 38
params: "stevenson2.prm"
box_dims:
  - [5.51, 6.82, 10.5]
  - [-5.51, -6.82, -10.5]
cell_shape:
  sg: None
  angles: [90, 90, 90]
meth_start: 3.0
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "temp"
  - "press"
velocity: "none"