xyz: "tianle_16.xyz"
sim: equil
center: True
population:
  acrylonitrile: 16
  methane: 26
params: "steveson2.prm"
# box_dims:
#   - [5.5, 6, 9.0]
#   - [-5.5, -6, -9.0]
box_dims:
  - [7, 7, 9.0]
  - [-7, -7, -9.0]
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "temp"
  - "press"
velocity: "none"