xyz: "rahm_unsolv_rehydrogen_reorg.xyz"
sim: freeze
center: True
population:
  acrylonitrile: 4
  methane: 13
params: "ligpargen.prm"
box_dims:
  - [1.6, 4, 9.0]
  - [-1.6, -4, -9.0]
thermo:
  - "step"
  - "etotal"
  - "ke"
  - "pe"
  - "temp"
  - "press"
velocity: "none"